### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by WilliamIX** [biocircuits/bioscrape#11]
We need to keep the wiki up to date.

Documentation needed for:

- SBML usage

- Lineages

- Different simulator types

- Parameter Identification

- Developer Guide [how all the parts flow together]

**Comment by WilliamIX** [comment]
@ayush9pandey I just ported over the old bioscrape wiki except for the parameter inference part which is clearly dated compared to all your new examples - currently I just pointed people to the examples folder but has no other information. At some point, could you add some pointers to which notebooks to look at for what?

**Comment by ayush9pandey** [comment]
Thanks! Updated the wiki for inference as well.

**Comment by ayush9pandey** [comment]
The wiki is in much better shape now. I edited all pages, added examples, a new README..so I consider this issue resolved for now. Obviously, we need to keep improving the documentation!
