### ISSUE TITLE
How to write GeneralODERule to SBML?

### ISSUE THREAD

**Issue by ayush9pandey** [biocircuits/bioscrape#110]
SBML has a rule type called the "rate rule" which can have variables rates be specified (see here: http://sbml.org/Software/libSBML/5.18.0/docs/python-api/classlibsbml_1_1_rate_rule.html). This seems the right kind of rule to write Bioscrape `GeneralODERule` with.  However, SBML needs a `rule_variable` and a `rule_formula` object for a rule to be successfully created. I am not sure how to get these for the `GeneralODERule`. In particular, this line needs a fix : https://github.com/biocircuits/bioscrape/blob/571766ae4b05840b9dd91dd1d5d47b965f84e911/bioscrape/types.pyx#L2336

Uncomment the SBML writing [line number 72](https://github.com/biocircuits/bioscrape/blob/571766ae4b05840b9dd91dd1d5d47b965f84e911/tests/test_rules.py#L72) in `test_rules.py` to recreate this error.

**Comment by ayush9pandey** [comment]
In hindsight, this issue should have been a comment on #107

**Comment by WilliamIX** [comment]
That looks correct to me. Rule_Variable should be the LHS and rule_formula the RHS of `rule_dict['equation'].` 

One potential difference between SBML and Bioscrape is that rules can be applied to parameters OR species in Bioscrape. Can the SBML Rule Variable be a Species?

**Comment by ayush9pandey** [comment]
Yes, SBML rule can be species.

Can you check the test_rules.py line above, in there you have ode rules
with equation keyword and a target keyword but without LHS or RHS. I don't
understand how that works.

**Comment by WilliamIX** [comment]
I see -  I misremembered how the ODE rule works. For an ODE dX/dt = f(x), target = 'X' and equation = f(x) is the proper way to do this.

**Comment by ayush9pandey** [comment]
The issue is fixed now.
