### ISSUE TITLE
Stochastic Simulating of Styrene polymerization in free radicals

### ISSUE THREAD

**Issue by teddiclax** [biocircuits/bioscrape#122]
Good day. 

I have been searching for a simulation python module to produce the deterministic and stochastic simulation of the above research topic. Also, I have been studying the "Transcription Translation"  example provided. Since free radical polymerization is a growing chain reaction, I have found it challenging to # create the reaction tuple for this type of reaction. I will appreciate your assistance in writing it.

Kind regards,
Edward 

![reference_material_](https://user-images.githubusercontent.com/85592612/137402482-6e097bb3-624a-413e-8623-990dfc4625c0.PNG)

**Comment by ayush9pandey** [comment]
Hi Edward,

Please let us know if you have been able to fix this issue. Happy to help further, if needed. 

To answer the question above: You can create a for loop that generates species and propensities to iteratively create reaction tuples to add to a bioscrape model.
