### ISSUE TITLE
random number  as a parameter

### ISSUE THREAD

**Issue by TiamHeydari** [biocircuits/bioscrape#124]
Hi, love the package.
I am trying to make a customize model which has a random variable as one of the parameters (modeling extrinsic noise in det modeling).
How can I do that? I couldn't find a way around it so far,
Thanks,

**Comment by ayush9pandey** [comment]
Hi Tiam,

Sorry for the late response. Bioscrape supports stochastic simulations which allows for modeling of randomness and noise in deterministic modeling. Simply turn on stochastic simulation by setting `stochastic = True` in `py_simulate_model`. 

I don't think making one particular parameter random while keeping others deterministic while simulating is possible. However, you could generates the random sample value for that parameter (by using your own or scipy distributions) and sets it to the model using `Model.set_params({'random_parameter_name': random_sample_value})`. Then, simulate the model. 

Hopefully that is helpful. Please feel free to comment here if you have further questions.
