### ISSUE TITLE
odeint default simulation values in simulator.pyx cause long simulations

### ISSUE THREAD

**Issue by ayush9pandey** [biocircuits/bioscrape#133]
Setting default to suggested odeint defaults fixes this. 

Here are the odeint defaults:
```
hmax = 0
mxstep = 0
atol = 1.49012e-8
rtol = 1.49012e-8
```

EDIT: `mxstep` is the max allowed because bioscrape iteratively increases it allowing for solution of stiff problems. So, setting at 500000 is good.

**Comment by ayush9pandey** [comment]
`mxstep` used to be 500000 but odeint suggested default is 0. Having this set at 500000 seems to prevent odeintfailed warnings. Any ideas if this affects simulation computation time too much? @WilliamIX 

I'm happy to have it set at 500000 so that there aren't odeint warnings, but want to understand if it affects speedup.

**Comment by ananswam** [comment]
`odeint` is not great on stiff problems. I think what I had way back in the day is trying to solve with `mxstep` smaller and then re-trying a couple times with increased values if it fails. This way it's minimal extra effort on the cases that need it (which will run long anyway), and most of the time that branch doesn't trigger.

**Comment by ayush9pandey** [comment]
Yes, I think your design of increasing mxstep is still there and it works good. I did not look at that earlier. On further testing, having mxstep default set at 500000 works much better and that's only the max, so the speed is not affected. 

Thanks to @zjuradoq for helping with this!

**Comment by ayush9pandey** [comment]
This is fixed now in dev.
