### ISSUE TITLE
JOSS REVIEW - Contributing Guidelines

### ISSUE THREAD

**Issue by Robaina** [biocircuits/bioscrape#151]
Hi!

I'm one of the reviewers of this repo at [JOSS](https://github.com/openjournals/joss-reviews/issues/5057). First of all, congratulations on this well-documented and organized repo! 

I see that the README includes a section regarding [contribution guidelines](https://github.com/openjournals/joss-reviews/issues/5057). While this section contains minimal info, I think it would be great to extend it a little bit (e,g, setting a developer environment, general ways of contributing, etc). Perhaps even create a separate [CONTRIBUTING.md](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) file.

This is just a suggestion, though.

**Comment by ayush9pandey** [comment]
Thanks @Robaina for the suggestion! I have created a draft PR #155 that will fix this issue.

**Comment by ayush9pandey** [comment]
Fixed and merged to master with #160 (available as bioscrape v1.2.1)
