### ISSUE TITLE
JOSS Review - Advance example Notebook broken

### ISSUE THREAD

**Issue by Robaina** [biocircuits/bioscrape#152]
Hi! 

taking a look at the examples for the [JOSS review](https://github.com/openjournals/joss-reviews/issues/5057) I noticed that the notebook containing the [advanced example](https://github.com/biocircuits/bioscrape/blob/master/examples/Advanced%20Examples%20-%20Direct%20Simulator%20Instantiation.ipynb) is broken. I get an error message: Unexpected token "<" in JSON at position 71312. Most likely easily fixable.

**Comment by ayush9pandey** [comment]
Thanks @Robaina  for raising this issue. I have raised PR #154 to fix this. I will comment here once it's merged and then close the issue.

**Comment by Robaina** [comment]
Perfect!

**Comment by ayush9pandey** [comment]
Fixed and merged to master with #160 (available as bioscrape v1.2.1)
