### ISSUE TITLE
JOSS REVIEW - Statement of Need -> Target Audience

### ISSUE THREAD

**Issue by Robaina** [biocircuits/bioscrape#157]
Hi!

Me again, reviewing this [JOSS submissiojn](https://github.com/openjournals/joss-reviews/issues/5057).  Following JOSS guidelines, I see that you have included a nice Statement of Need in the manuscript. It clearly covers all points requested. However, there is a final point "Target audience" that I think could be stated explicitly in the manuscript,  i.e. bioscrape i built for researchers in "field, perhaps also educational?

Thanks!

**Comment by ayush9pandey** [comment]
Fixed in `joss-paper` branch.

**Comment by ayush9pandey** [comment]
Closing the issue as joss-paper branch will automatically update the paper in the review issue: https://github.com/openjournals/joss-reviews/issues/5057 

The branch will not be merged to bioscrape master.
