### ISSUE TITLE
JOSS Review -- A list of minor comments

### ISSUE THREAD

**Issue by Farnazmdi** [biocircuits/bioscrape#163]
Congratulations on developing this package, it is very well written and super useful in its relevant field. I just have a few minor comments.

In the manuscript:

- [x] line 44, "from" is repeated.
- [x] line 19 "partioning" is a typo.
- [x] in figure 1a, the word "Transcription fixed delay" has a typo.
- [x] It would be nice to accompany the figure1b with a mathematical equation to clarify if there is a simple closed form expression for it.

In the repository:

- [x] I see that some of the functions have extensive documentation, but it would be clearer if all functions had this, especially specifying the type of the input arguments, such as 'int', 'float', etc. would help with readability of the functions.
- [x] This one is just a suggestion and mostly my curiosity to see how does Numpyro perform versus your implementation of MCMC inference in Cython. Do you have an idea about this?
- [x] It would be nice to add a link or some explanation on how to install jupyter notebook kernels in the installation guide. In case somenone wants to clone your repository I guess it would be necessary to install a kernel.

**Comment by ayush9pandey** [comment]
Thanks @Farnazmdi for reviewing bioscrape! I will work on fixing these.

Just want to point you to the latest paper PDF https://raw.githubusercontent.com/openjournals/joss-papers/joss.05057/joss.05057/10.21105.joss.05057.pdf
(also available on the review thread). The update after the previous review fixed the typo error so I have marked that task as done.

Will get back to you about the other issues in this thread.

**Comment by ayush9pandey** [comment]
- Added instructions about Jupyter notebooks in the Installation page on the Wiki.

**Comment by ayush9pandey** [comment]
- Added docstrings and types of arguments to all user interface functions. We understand that a detailed documentation of the code is an important software engineering practice. The current status of the documentation is in no way complete or up-to industry standards. So, we will keep improving the documentation of the package. 
- For now, I have added a detailed docstring and argument types to all four key functionalities of bioscrape: model construction using `Model` class constructor, all user-level analysis functions in the `analysis` module, the inference module's user interface function `py_inference`, the simulation function `py_simulate_model`.

All of these changes are on the `documentation` branch that will be merged soon!

**Comment by ayush9pandey** [comment]
- Discussion on speeding up inference is on #38 .

**Comment by ayush9pandey** [comment]
- For Figure 1b, since we also have a `delay` in the model, there is no "nice looking" closed form expression for the model. The `delay` for each reaction in bioscrape is a probabilistic delay in firing of propensity of that reaction. So, I'm not sure if there is a good closed form expression to write it.

**Comment by ayush9pandey** [comment]
- Fixed paper typos in the `joss-paper` branch.

**Comment by ayush9pandey** [comment]
Hi @Farnazmdi ,

Thanks for reviewing bioscrape. Please let me know if the fixes that I have described are satisfactory and if you have other comments.

**Comment by Farnazmdi** [comment]
Hi @ayush9pandey Thanks for addressing the comments. I believe these changes resolve all my concerns. Wonderful job!
