### ISSUE TITLE
What if a reaction includes inputs not in its rate function?

### ISSUE THREAD

**Issue by WilliamIX** [biocircuits/bioscrape#19]
In general, bioscrape allows propensities to be arbitrary functions. However, these can result in the values of certain species going below 0 if the propensity function doesn't go to 0 with these species. Most well-thought-out models don't have this problem (eg standard usage of hill function and mass action propensities) - but non-standard usage could present issues. SSA safemode simulation catches these kinds of errors, however there is no ODE safemode. 

One simple solution is to warn users that they have created a propensity which has inputs not in its rate function.

Another option would be to build an ODE safemode to check these erros.

Why not just make propensities check that their inputs are non-zero? Mainly because this would be computationally expensive at runtime and most normal uses of massaction propensities and hill functions do not have this issue.

**Comment by ayush9pandey** [comment]
I wouldn't prefer having yet another warning pop-up for this issue (we already have too many in my opinion). I like the ODE safemode option.

**Comment by WilliamIX** [comment]
Fixed in Dev - will push to master soon.
