### ISSUE TITLE
Redundant SBML-reading functions

### ISSUE THREAD

**Issue by sclamons** [biocircuits/bioscrape#20]
There are currently at least three ways to create a bioscrape.Model object from an SBML file:

1. Model's constructor can take the name of an SBML file. If you use this method, the Model will convert the SBML file directly to bioscrape XML, then use its import-from-XML function on the resulting string. 
2. A read_model_from_sbml function in types.pyx wraps the above constructor.
3. types.pyx's import_sbml function parses the SBML file using libsbml and directly builds a Model object. 

We should pick one to be the standard way to do things and deprecate the rest. Otherwise, any time we want to change how we use SBML files (or import them), we're going to risk creating conflicting versions. Thoughts on which we should use? I'm generally in favor of deprecating the XML language where possible, so my vote would be to stick with #3.

**Comment by WilliamIX** [comment]
Did you check this on the newest version of bioscrape master which we pushed on Thursday? I believe I fixed these problems last week - but maybe I missed something.

**Comment by ayush9pandey** [comment]
> 1. Model's constructor can take the name of an SBML file. If you use this method, the Model will convert the SBML file directly to bioscrape XML, then use its import-from-XML function on the resulting string.
This has been fixed in an earlier [PR](https://github.com/ananswam/bioscrape/pull/46) that is updated on this repository as well. 

> 2. A read_model_from_sbml function in types.pyx wraps the above constructor.
Fixed with [PR](https://github.com/ananswam/bioscrape/pull/46).

> 3. types.pyx's import_sbml function parses the SBML file using libsbml and directly builds a Model object.
Now moved to sbmlutil module and is the standard way to import. Directly calling with the `Model` constructor also calls this method internally. 

Closing the issue.
