### ISSUE TITLE
Question : Is additive rule type a special case of a general assignment rule type?

### ISSUE THREAD

**Issue by ayush9pandey** [biocircuits/bioscrape#23]
(From the Wiki for Rules)
There are two main types of rules:
1. "additive": used for calculating the total of many species. Rule 'equation' must be in the form $s_0 = s_1 + s_2 ...$ where $s_i$ each represents a species string.
2. "assignment": a general rule type with 'equation' of the form $v = f(s, p)$ where $v$ can be either a species or parameter which is assigned the value $f(s, p)$ where $s$ are all the species and $p$ are all the parameters in the model and $f$ is written as an string.

Since $s_0$ will be a species in the model for the additive rule, can we instead use the assignment rule type where the function is simply the sum of all species? Is there some computational advantage to using additive rule? Or am I missing something.

**Comment by WilliamIX** [comment]
yes - additive rules are coded for speed [similar to general propensities versus specific propensity types]
