### ISSUE TITLE
Bioscrape wiki/installation steps are missing

### ISSUE THREAD

**Issue by ayush9pandey** [biocircuits/bioscrape#41]
Do we want to copy all of that over from ananswam/bioscrape ?

**Comment by murrayrm** [comment]
I think we should talk about where we want the documentation for bioscrape to live and where we want the installation instructions to leave.  Installation instructions can go in `README.md` and that will show up on the GitHub main page.

Documentation is currently on Anandh's wiki, but this is probably not the right place.  For packages that people import and call (versus a program that you run), I prefer to use something like `sphinx` to extract documentation from docstrings and then add documentation through a specific `doc/` directory.  This can all be automatically compiled and placed on `readthedocs` or another web site.  See https://python-control.readthedocs.io for an example.

**Comment by ayush9pandey** [comment]
I agree that something like `sphinx` might be a good way forward. We would need to add docstrings to the classes and functions consistently.

For now, the old Installation steps and minimal documentation has been ported over from ananswam/bioscrape, so we have some documentation on the Github Wiki. So, I am closing this issue and opening #49.
