### ISSUE TITLE
Perfect volume splitter creating species de novo

### ISSUE THREAD

**Issue by mkratz** [biocircuits/bioscrape#42]
When using the 'perfect' setting as default for the LineageVolumeSplitter class, species that are seeded at 0, and have no direct mechanism producing them (should stay at zero during entire simulation) go from being at 0 to 1 upon the first cell division. 

Simple example attached as txt:

[LG_BUG.txt](https://github.com/biocircuits/bioscrape/files/4714564/LG_BUG.txt)

**Comment by WilliamIX** [comment]
fixed with PR merge to dev
