### ISSUE TITLE
int vs lon type error again

### ISSUE THREAD

**Issue by sophiejwalton** [biocircuits/bioscrape#44]
Hi everyone,

I am using a Mac, and when I run 
py_SimulateInteractingCellLineage I get the following error:

ValueError                                Traceback (most recent call last)
<ipython-input-11-2c40a9c28cb8> in <module>
      3                                                  initial_cell_states = initial_cell_counts,
      4                                                  global_species = global_species,
----> 5                                                  average_dist_threshold = average_dist_threshold)

lineage/lineage.pyx in bioscrape.lineage.py_SimulateInteractingCellLineage()

lineage/lineage.pyx in bioscrape.lineage.InteractingLineageSSASimulator.py_SimulateInteractingCellLineage()

lineage/lineage.pyx in bioscrape.lineage.InteractingLineageSSASimulator.SimulateInteractingCellLineage()

ValueError: Buffer dtype mismatch, expected 'int' but got 'long'

This is just using an example notebook. I do not have this issue when I run other lineage functions. 

Sophie

**Comment by WilliamIX** [comment]
Have you updated to the newest version of the LineageBeta branch? I thought @sclamons had fixed this problem.

**Comment by sclamons** [comment]
There was another one. I'm pretty sure I patched this yesterday -- if someone else can confirm that it now works, we can close this one.

**Comment by sclamons** [comment]
Incidentally, the signature for this bug seems to be trying to use ndarray.astype, which simply doesn't seem to do anything in Cython, on a numpy array that wasn't initialized with the correct type. The fix is to get rid of the astype call and initialize correctly the first time.

**Comment by sophiejwalton** [comment]
It is fixed I think- the function runs without the Lon vs int error

**Comment by WilliamIX** [comment]
@sophiejwalton did you fix this issue in the bioscrape code? If so, please make a pull request if you fixed this issue in the bioscrape code so that other people can benefit from your fix. If it was just an issue with the parameters you put into your code, could you please explain the fix so that I can add a check the py_simulate function?

**Comment by sclamons** [comment]
sophiejwalton was confirming that the fix I pushed worked. I'm closing.
