### ISSUE TITLE
Unit Testing Discussion

### ISSUE THREAD

**Issue by WilliamIX** [biocircuits/bioscrape#5]
@sclamons has developed a great unit testing framework which we should absolutely use for all features (and all new features). To see examples of "how to write bioscrape tests.ipynb" in https://github.com/biocircuits/bioscrape/tree/integration_tests/tests on the integration tests branch. Below, we need to decide a managable set of tests that covers all the core bioscrape features.

**Comment by WilliamIX** [comment]
The challenge in testing individual objects is that without connecting them to a model, a lot of their functionality requires cython code and/or new python function wrappers around cython code. To avoid all that coding, I suggest we test all objects connected to a bioscrape model. Here is a preliminary list for the core bioscrape features. Once we get these core tests created, we can come back to lineage and system identification tests. @ayush9pandey @sclamons feedback would be appreciated.

1. Bioscrape.types.Model: Ensure it instantiates as an empty object.
2. Bioscrape.simulator.ModelCSimInterfaceand SafeModelCSimInterface: Ensure they instantiate when connected to an empty model.
3. All Bioscrape.simulator Simulator objects should instantiate: DeterministicSimulator, SSASimulator, VolumeSSASimulator, DelaySSASimulator, DelayVolumeSSASimulator. For now, lets hold of on testing any cell lineage features. I also suggest we begin deprecating: DeterministicDilutionSimulator (people should just add the reactions they want). SafeModeSSASimulator (this has been replaced with the safe interface). TimeDependentSSASimulator (I don't know what this does that SSA doesnt).
5. Simple Models consisting of one reaction should be tested to make sure all propensity and delay objects work for Deterministic, SSA, VolumeSSA, DelaySSA, and VolumeDelaySSA simulation types.
6. One rule of each type (assignment and additive) should be tested for all simulation types.
7. Wrapper function py_simulate_model should be tested for deterministic, ssa, and safemode ssa settings for one model.
8. SBML reading and writing should be tested for all propensity types and rule types. Delays not supported by SBML [later this support will be added via SBML annotations].

**Comment by sclamons** [comment]
1. Have you had bugs around this before? I'm not sure we learn much just by instantiating (though I guess it's not a hard test to throw in).
2. Ditto #1.
3. It wouldn't be difficult to add a couple of lineage-tracking integration tests. Also, DeterministicDilutionSimulator seems like a nice convenience feature. The other two look depricatable to me.
4. Sounds good to me. 
5. Sounds good to me.
6. Sounds good to me.
7. Sounds good to me. Right now, I'm putting together a function to automate SBML read/writes in a way similar to the model-testing function. Should make it trivial to test SBML read/writing for every model we ever test.

**Comment by sclamons** [comment]
One problem -- do we have any way to write models to SBML right now? I can't find one.

**Comment by WilliamIX** [comment]
yes - we can write everything but general propensities and rules to SBML as of last week. General propensities and rules are coming next.

See sbmlutils.py for all the relevant helper functions and Model._generate_sbml_model and Model.write_sbml. There are also examples in ipython notebooks from Thursday's class and in the tests folder.

We have SBML loading and writing capabilities, which call a built-in function in SBML that checks the SBML model.

**Comment by WilliamIX** [comment]
In regards to the test cases:
1. Only had problems with this when I wrote the API and changed how a lot of things worked. I could imagine deep changes in the code causing problems - but I agree this could probably be skipped / is implicitly tested in all the other 
2. I Am happy to test these implicitly through the simulation tests - the reason I put this here is because after talking to you it sounded like you thought it was better practice to test things as "individually as possible".
3. Let's get to lineage testing in the same format in a future release - I anticipate a lot of lineage development in the next month or so and after all that work we can build a comprehensive set of tests. In general, the lineage framework will put out a very different kind of output (lineage objects) which will probably require a modified testing routine.

**Comment by WilliamIX** [comment]
@sclamons thanks for your help on this. I think we have essential unit testing for bioscrape core set up now, so I will close this issue.
