### ISSUE TITLE
General propensity reaction fires when rate is 0 

### ISSUE THREAD

**Issue by rlwillia** [biocircuits/bioscrape#55]
The error occurs when using M.create_reaction() when using a general propensity, specifically when the species that is being produced has a non-zero starting concentration. If the reaction reaction rate is 0 (or if you use a parameter for rate which has a value of zero), the species that is produced by the reaction is produced. We initially saw this error when using the Heaviside function in the general propensity and the reaction fired even when the quantity within the Heaviside function was negative, and continued to see the same error when just having the "rate" be 0.

[general_propensity_error.ipynb.zip](https://github.com/biocircuits/bioscrape/files/5018973/general_propensity_error.ipynb.zip)

**Comment by WilliamIX** [comment]
I have been able to successfully recreate this issue. Additionally, it seems that the SBML files generated from both cases in the ipython notebook look identical. I am at a loss as to what is going on.
