### ISSUE TITLE
Model objects (and presumably others) can't be copied with Python's copy.copy because they can't be pickled..

### ISSUE THREAD

**Issue by sclamons** [biocircuits/bioscrape#57]
Apparently copy.copy() can only copy objects that can be pickled. CPython doesn't, by default, know how to pickle Cython objects with pointer variables. Model objects have lots of pointers. Therefore, Model objects can't be copied. 

It would be quite useful to be able to copy Model objects -- for example, to build variations on a Model without affecting the original. 

Two possible fixes:
1) Add a copy method to Model that does the copying manually. This is probably easier than (2).
2) Add a `_reduce_()` function to Model, as discussed [here](https://stackoverflow.com/questions/12646436/pickle-cython-class), [here](https://stackoverflow.com/questions/36301322/pickle-cython-class-with-c-pointers), and [here](https://cython.readthedocs.io/en/latest/src/userguide/extension_types.html). **This also allows the use of Model objects in multiprocessed Python functions**, and so is the preferred solution if someone can do it.

**Comment by WilliamIX** [comment]
The way I typically deal with this (for multiprocessing) is have each new thread instantiate a new model from the species, reactions, rules, and parameters. I think we could easily add a copy method as well.

I think the reduce option would be doable as well - but how we do it very much depends on the workflow you are aiming for. @sclamons can you elaborate on how you are trying to copy/pickle objects and to what end so this can be designed appropriately.

**Comment by WilliamIX** [comment]
@sclamons I think you have fixed this in your latest PR?

**Comment by sclamons** [comment]
Yep, I think we can close.
