### ISSUE TITLE
General wrapper to use any scipy distribution as a prior

### ISSUE THREAD

**Issue by WilliamIX** [biocircuits/bioscrape#63]
The idea here is to dramatically extend our allowable priors by allowing any scipy distribution to be used as a prior. Ideally, the user can pass in a scipy distribution and then bioscrape inference will figure out this is a scipy distribution and use it correctly. Alternatively, we can create a ScipyPrior(scipy_dist) wrapper which is passed in.

@sclamons did I reiterate your idea correctly?

**Comment by sclamons** [comment]
Yep, this is what I want.

**Comment by ayush9pandey** [comment]
Fixed in #76. Now you can use a "custom" prior to define your own log-prior function. Check out the prior notebook in inference examples and the documentation on Wiki.
