### ISSUE TITLE
edit installation instructions on the wiki

### ISSUE THREAD

**Issue by zoltuz** [biocircuits/bioscrape#72]
[The installation instructions](https://github.com/biocircuits/bioscrape/wiki/Installation#setup-instructions) recommend running
```
python setup.py install
```
The problem is that setup.py does not contain the required packages for installation. 

Solution: edit the wiki page by adding the following:

Before install, please run
```
pip install -r requirements.txt
```

**Comment by WilliamIX** [comment]
pip install bioscrape now works and this issue is being closed.
