### ISSUE TITLE
Gaussian prior minor bug in probability computation

### ISSUE THREAD

**Issue by ayush9pandey** [biocircuits/bioscrape#79]
This is a minor bug with Gaussian prior in bioscrape inference but causes wrong computations..will be fixed soon.

**Comment by ayush9pandey** [comment]
It's fixed in the inference-dev branch until then.

**Comment by WilliamIX** [comment]
@ayush9pandey is this fixed?

**Comment by ayush9pandey** [comment]
Fixed with #102
