### ISSUE TITLE
installation process only works if bioscrape installed in the current folder

### ISSUE THREAD

**Issue by zoltuz** [biocircuits/bioscrape#81]
The installation guide says to run
```
python setup.py install
```
but this command only works if bioscrape files are in the current folder. For example, this fails:
```
python ../../Downloads/bioscrape-master/setup.py install
```
Cause: There are OS calls with absolute path backed into the setup.py

**Comment by WilliamIX** [comment]
I believe this is fixed with `pip install bioscrape` - @zoltuz please confirm

**Comment by zoltuz** [comment]
I've tried but had some issues as reported in #88

**Comment by ayush9pandey** [comment]
Is this fixed now?

**Comment by WilliamIX** [comment]
pip install works now.
