### ISSUE TITLE
installation issue with installed with pip

### ISSUE THREAD

**Issue by zoltuz** [biocircuits/bioscrape#88]
Hi all,
I've tried to install bioscrape via pip, in a new virtual environment, but I got this error:
<img width="1171" alt="Screenshot 2021-01-16 at 14 02 39" src="https://user-images.githubusercontent.com/17138838/104813874-c947bc80-5803-11eb-901c-d9bd143bb118.png">
It looks like, it tries to install bioscrape without installing numpy first. Maybe the order of dependencies needs some tweaking in the `setup.py`

## Steps to recreate the problem:
```
mkdir  test_bioscrape
cd test_bioscrape
python -m venv ./venv
source venv/bin/activate           
pip install bioscrape       
```

**Comment by WilliamIX** [comment]
Thanks! I will take a look.

**Comment by WilliamIX** [comment]
@zoltuz I believe I fixed this issue, could you please check?

**Comment by zoltuz** [comment]
yep, the installation works now:
<img width="1047" alt="Screenshot 2021-01-17 at 10 22 54" src="https://user-images.githubusercontent.com/17138838/104837805-da99d300-58ae-11eb-82d6-094b40c49152.png">
