### ISSUE TITLE
Build a set of Priors Objects for Parameter Identification

### ISSUE THREAD

**Issue by WilliamIX** [biocircuits/bioscrape#9]
What priors do we need? Initial class types:
1. Uniform
2. Log-uniform
3. Gaussian
4. Custom [cython interface that wraps a passed in python function - might be slower, but effective for specific cases]

I believe the framework for them is there waiting...

**Comment by WilliamIX** [comment]
Positivity (>= 0) should be an option for every Prior - maybe we can bake that into the underlying prior class with a flag (it could be turned off for parameters that aren't rate constants)

@sclamons you mentioned some sources of good prior models we could add in class - could you post a reference?

**Comment by WilliamIX** [comment]
Suggestions from the class:

- log-normal
- gamma
- exponential
- Beta

**Comment by sclamons** [comment]
Recommended reading:
https://betanalpha.github.io/assets/case_studies/probability_densities.html

Those distributions gives you a lot to work with. Might want to include
inverse gamma, too.

**Comment by ayush9pandey** [comment]
I have added the framework for most of these in bioscrape inference. Currently they raise a NotImplementedError, but as we get use cases and people willing to write these down we will get more priors.

I also added a custom prior which can take a callable function as an argument to compute the log prior probabilities.

**Comment by ayush9pandey** [comment]
Fixed with #50.
