### ISSUE TITLE
Lineage.py_get_schnitz() crashes the kernel if called with an out-of-bounds index.

### ISSUE THREAD

**Issue by sclamons** [biocircuits/bioscrape#95]
For a `Lineage` object `my_lineage`, `my_lineage.py_get_schnitz(my_lineage.py_get_size())` will attempt to access my_lineage.c_schnitzes -- which is a Cython array -- out of bounds, which crashes the kernel instead of throwing an exception. Needs an array bounds check to fail gracefully.

**Comment by WilliamIX** [comment]
excellent catch! We should fix this. I wonder if there are other places where this kind of thing happens. Any thoughts on how to check through all the vectors?

**Comment by sclamons** [comment]
This one in particular can be fixed by checking bounds against the length
of the python version of the schnitzes array... which I think makes it just
as slow as just returning a Schnitz directly from the python array?

>

**Comment by WilliamIX** [comment]
Fixed with PR merge to dev
