### ISSUE TITLE
Rules do not fire if no reactions can occur.

### ISSUE THREAD

**Issue by sclamons** [biocircuits/bioscrape#96]
Just made a test involving a Model with a rule to add inducer at some set time. The inducer doesn't do anything -- it's just there to test Rule functionality. As it happens, when I simulate (stochastically), the simulation effectively ends at some time _t_ because a key reactant _A_ runs out and can't be replaced. 

Everything works fine _if_ I set the inducer to be added before _t_. If I nudge the induction time so that the inducer is added _after_ _t_, even just slightly, then the rule seemingly never fires and the inducer never gets added. This could matter a lot if, for example, the inducer caused production of _A_. 

I suspect this is happening either because a) the SSA simulator only checks rules when a species changes state (which never happens if there are no more possible reactions) or b) because the SSA simulator can tell that there are no more possible reactions and skips ahead to the end.

**Comment by sclamons** [comment]
(The model in question is one of the models in a serialization test I'm currently writing. I'll try to remember to update this with a more specific reference when the test gets added to the repo.)

**Comment by sclamons** [comment]
Behavior can be seen in `test_serialization.py`, in `tests`, in the first test (`test_random_complex_model`). If you plot out all of the species in `prepickling_results` (or `postpickling_results`, they're identical), you'll see `I` jump up from 0 to 10 concentration at _t_=2. If you change `M.create_parameter("T_I0", 2)` to `M.create_parameter("T_I0", 3)`, you'll see the jump fails to happen.

**Comment by WilliamIX** [comment]
More specifically, in standard SSA simulator (and potentially in the Lineage SimualteSingleCell) rule applications can be skipped if reactions fire far apart as the simulator will jump to the next fire time without applying rules inbetween.
