### ISSUE TITLE
Deprecate Bioscrape XML and Replace with SBML

### ISSUE THREAD

**Issue by WilliamIX** [biocircuits/bioscrape#99]
- [x] Add new rule types to SBML reading and writing (issue #107 ) [AP]
- [x] Add delays to SBML reading/writing using annotations [AP]
- [x] Remove all examples that use Bioscrape XML [WP]
- [x] Remove bioscrape XML writing code.  Keep bioscrape XML reading code. [WP]
- [x] Tests that every rule and propensity type and delay type reads and writes correctly (with and without annotations) [WP]
- [x] Confirm underscores are consistently removed from the start of parameters and not added. Concerned about line 476 of sbmlutil.py (and there are some other places...) maybe we could test for this? [AP]

**Comment by ayush9pandey** [comment]
For checklist point #5 I have added tests to verify delay annotations reading and writing with SBML correctly, along with checking the simulations for the model. Similar tests for propensities exist already. Marking it done for now - but feel free to check this again on your end and add more tests if needed.

**Comment by WilliamIX** [comment]
Tests looked great and very comprehensive. Closing this issue.
